version: '3'
services:
  web:
          build: .
          ports:
                  - "82:80"
  db:
          image: mysql
          ports:
                  - "3336:3306"
          environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_USER=user
          - MYSQL_PASSWORD=password
          - MYSQL_DATABASE=demodb
